#:schema node_modules/wrangler/config-schema.json
name = "caller-square-mud-fa69"
main = "src/index.ts"
compatibility_date = "2024-06-03"
compatibility_flags = ["nodejs_compat"]

services = [
	{ binding = "CALCULATOR", service = "calculator-red-snow-a48d" },
]
